language: python
python:
  - "3.8"
install: pip install -r requirements.txt
script:
  - python manage.py test apps.repostrend.tests
  - coverage combine
  - codecov --token=bef1309c-70d5-4ee8-a384-f64bba88da9d
